import type { Spot, Verb } from "@/lib/game/world";

function act(partial: Partial<Verb> & Pick<Verb, "id" | "label" | "detail">): Verb {
  return { minutes: 40, cost: 0, earn: 0, effects: {}, ...partial };
}

function at(originX: number, originY: number, index: number, cols = 3) {
  const col = index % cols;
  const row = Math.floor(index / cols);
  return { x: originX + col * 64, y: originY + row * 52 };
}

const dance = (id: string, detail: string, cost = 48): Verb =>
  act({
    id,
    label: "Dance",
    detail,
    minutes: 110,
    cost,
    effects: { fun: 34, energy: -16, social: 16, hygiene: -10, bladder: -10 },
    tag: "party",
    skill: "music",
    social: true,
  });

const sip = (id: string, label: string, detail: string, cost = 24): Verb =>
  act({
    id,
    label,
    detail,
    minutes: 55,
    cost,
    effects: { fun: 18, social: 12 },
    tag: "party",
    social: true,
  });

const plate = (id: string, label: string, detail: string, cost = 18): Verb =>
  act({
    id,
    label,
    detail,
    minutes: 35,
    cost,
    effects: { hunger: 36, fun: 8, social: 6 },
    tag: "food",
    social: true,
  });

const stroll = (id: string, label: string, detail: string, cost = 0): Verb =>
  act({
    id,
    label,
    detail,
    minutes: 40,
    cost,
    effects: { fun: 18, energy: -4, social: 6 },
    social: true,
  });

export const CLUB_IDS = new Set([
  "twist",
  "mad-club",
  "ace-tantra",
  "tantra",
  "duplex",
  "bella-roma",
  "front-back",
  "embar",
  "one-percent",
  "zen-garden",
  "afrikiko",
  "bloom",
  "monsoon",
  "republic",
  "still",
  "plus233",
]);

/** Food-first rooms — calm lively playlist, not club heat. */
export const EATERY_IDS = new Set([
  "auntie-muni",
  "asanka",
  "jamestown-coffee",
  "kishitei",
  "dez-amis",
  "vine-brasa",
  "honeysuckle",
  "la-borracha",
  "el-padrino",
  "polo-club",
  "lizzys",
]);

export const ACCRA_SPOTS: Spot[] = [
  {
    id: "twist",
    name: "Twist",
    emoji: "🪩",
    ...at(1400, 620, 0),
    group: "hang",
    blurb: "Labone. A wide floor, a local crowd, and DJs who keep the room moving.",
    actions: [dance("twist-dance", "The floor fills before you find your people."), sip("twist-bar", "Hold the rail", "One drink at the edge while the bass does the talking.", 28)],
  },
  {
    id: "mad-club",
    name: "Mad Club",
    emoji: "🪩",
    ...at(1700, 300, 0),
    group: "hang",
    blurb: "East Legon. Glossy room, late door, the kind of night people plan the outfit for.",
    actions: [dance("mad-dance", "Lights low, shoes off the guest list in your head.", 55), sip("mad-booth", "Take a booth", "You sit where you can see who just walked in.", 36)],
  },
  {
    id: "ace-tantra",
    name: "Ace Tantra",
    emoji: "🪩",
    ...at(1400, 620, 1),
    group: "hang",
    blurb: "Labone. A club still finding its shape, loud enough that the street knows.",
    actions: [dance("ace-dance", "You stay for the second DJ, not the first."), sip("ace-drink", "Buy a round", "The round is for two. You drink one.", 26)],
  },
  {
    id: "tantra",
    name: "Tantra",
    emoji: "🌙",
    ...at(1400, 620, 2),
    group: "hang",
    blurb: "Labone. Best after midnight. Electronic, R&B, expats and Accra in the same queue.",
    actions: [dance("tantra-dance", "Midnight is when the room actually starts.", 50), sip("tantra-late", "Stay till late", "The city outside has gone quiet. In here it has not.", 30)],
  },
  {
    id: "duplex",
    name: "Duplex",
    emoji: "🪩",
    ...at(1400, 620, 3),
    group: "hang",
    blurb: "Labone. Two levels, a mixed crowd, and a playlist that sits near Tantra's.",
    actions: [dance("duplex-dance", "Upstairs for the view, downstairs when the song hits."), sip("duplex-up", "Upstairs drink", "You watch the floor from the rail.", 32)],
  },
  {
    id: "bella-roma",
    name: "Bella Roma",
    emoji: "🍝",
    ...at(1400, 620, 4),
    group: "hang",
    blurb: "Labone. Italian plates early. After ten the room turns into a bar.",
    actions: [plate("bella-pasta", "Eat before the flip", "A proper plate while the chairs are still for sitting.", 32), dance("bella-late", "The tables move and the night takes the floor.", 40)],
  },
  {
    id: "front-back",
    name: "Front/Back",
    emoji: "🚪",
    ...at(900, 740, 0),
    group: "hang",
    blurb: "Osu. One door for the early crowd, another for whoever is still out.",
    actions: [sip("fb-front", "Start in front", "You arrive while the street is still part of the party.", 22), dance("fb-back", "The back room is where the night agrees to continue.", 42)],
  },
  {
    id: "embar",
    name: "Embar",
    emoji: "🖤",
    x: 1760,
    y: 420,
    group: "hang",
    blurb: "East Legon. Members at the door. The room is small and the lighting is doing a job.",
    actions: [sip("embar-door", "Ask at the door", "Your name is not on the list. A guest still gets you in.", 70), dance("embar-floor", "Nobody is filming. That is the point.", 60)],
  },
  {
    id: "one-percent",
    name: "One Percent",
    emoji: "🖤",
    x: 1840,
    y: 420,
    group: "hang",
    blurb: "East Legon. Another members room. Dress like you already belong.",
    actions: [sip("percent-door", "Guest list", "You borrow a name and pay for the privilege.", 75), sip("percent-quiet", "A quiet corner", "The music is present. The shouting is not.", 40)],
  },
  {
    id: "bloom",
    name: "Bloom Bar",
    emoji: "🌸",
    ...at(900, 740, 1),
    group: "hang",
    blurb: "Osu. A long-standing room where the crowd mixes without a speech about it.",
    actions: [sip("bloom-drink", "Take a table", "You came for one and the table has other plans."), stroll("bloom-street", "Step outside", "Oxford Street is the second bar.")],
  },
  {
    id: "monsoon",
    name: "Monsoon",
    emoji: "🌧️",
    ...at(900, 740, 2),
    group: "hang",
    blurb: "Osu. Oxford Street terrace, weekend DJs, and three kitchens if you are hungry.",
    actions: [sip("monsoon-terrace", "Sit on the terrace", "The street is the show. The DJ is the soundtrack.", 26), plate("monsoon-kitchen", "Order from the kitchen", "You eat before the terrace gets too loud to talk.", 30)],
  },
  {
    id: "lizzys",
    name: "Lizzy's",
    emoji: "🔊",
    ...at(900, 740, 3),
    group: "hang",
    blurb: "Osu. Plastic chairs, big speakers, and Accra actually in the circle.",
    actions: [sip("lizzys-chair", "Take a chair", "The chair is free. The speaker is the rent.", 12), stroll("lizzys-corner", "Stay on the corner", "You learn the street by standing still.")],
  },
  {
    id: "ritual",
    name: "Ritual",
    emoji: "🎧",
    x: 800,
    y: 480,
    group: "hang",
    blurb: "Ringway Estates. A listening bar. Strong drinks, small chops, soft records.",
    actions: [sip("ritual-listen", "Listen", "The DJ is not asking you to shout.", 28), plate("ritual-chops", "Small chops", "Something salty so the drink has company.", 16)],
  },
  {
    id: "skybar25",
    name: "Skybar25",
    emoji: "🌆",
    ...at(1580, 80, 0, 2),
    group: "hang",
    blurb: "Airport City. Rooftop, the skyline on every side, sundowners if you time it.",
    actions: [sip("sky-sundown", "Sundowner", "The city goes gold and your glass goes empty.", 34), stroll("sky-rail", "Walk the rail", "You look for your own neighbourhood in the lights.")],
  },
  {
    id: "hayvin",
    name: "The Hayvin",
    emoji: "🌿",
    ...at(1700, 300, 1),
    group: "hang",
    blurb: "East Legon. Open air, greenery, cabanas, and the roofs of the neighbourhood below.",
    actions: [sip("hayvin-cabana", "Take a cabana", "Shade, a low table, nobody rushing you.", 32), stroll("hayvin-garden", "Walk the garden", "The plants are doing more work than the playlist.")],
  },
  {
    id: "exhale",
    name: "Exhale Lounge",
    emoji: "💨",
    ...at(1700, 300, 2),
    group: "hang",
    blurb: "East Legon. Open-air lounge. Cocktails, and a night that does not need a dancefloor.",
    actions: [sip("exhale-cocktail", "Order a cocktail", "Pretty glass. You still know what is in it.", 30), sip("exhale-stay", "Stay out", "The air is the amenity.", 18)],
  },
  {
    id: "firefly",
    name: "Firefly",
    emoji: "✨",
    ...at(900, 740, 4),
    group: "hang",
    blurb: "Osu. Cocktails, music, and a room built for mingling.",
    actions: [sip("firefly-mix", "Mingle", "You talk to two strangers and leave with one number.", 26)],
  },
  {
    id: "honeysuckle",
    name: "Honeysuckle",
    emoji: "🍯",
    ...at(1400, 620, 5),
    group: "hang",
    blurb: "Labone. Specialty drinks, and chicken wings that justify the stop.",
    actions: [sip("honey-drink", "Specialty drink", "You let them choose. It works.", 26), plate("honey-wings", "Chicken wings", "Crisp, messy, worth the napkin.", 22)],
  },
  {
    id: "la-borracha",
    name: "La Borracha",
    emoji: "🌮",
    ...at(1400, 620, 6),
    group: "hang",
    blurb: "Labone. Sangria by night, tacos if you arrive before the crawl starts.",
    actions: [plate("borracha-taco", "Tacos", "Daytime portion. Night can wait.", 24), sip("borracha-sangria", "Sangria", "The jug arrives and the plan changes.", 20)],
  },
  {
    id: "purple-pub",
    name: "Purple Pub",
    emoji: "🟣",
    ...at(900, 740, 5),
    group: "hang",
    blurb: "Osu. A purple room that has been part of this street for years.",
    actions: [sip("purple-pint", "Stay for a round", "The street changes. The pub keeps its colour.", 16)],
  },
  {
    id: "duncans",
    name: "Duncan's",
    emoji: "🪑",
    ...at(900, 740, 6),
    group: "hang",
    blurb: "Osu. Outdoor, easy, the kind of stop that becomes the whole evening.",
    actions: [sip("duncans-outdoor", "Sit outside", "No agenda. The chair does the work.", 14)],
  },
  {
    id: "ryans",
    name: "Ryan's Irish Pub",
    emoji: "🍺",
    ...at(900, 740, 7),
    group: "hang",
    blurb: "Osu. A pint when you want the night to stay ordinary.",
    actions: [sip("ryans-pint", "Have a pint", "Quiet room. That is the feature.", 18)],
  },
  {
    id: "container",
    name: "Container",
    emoji: "📦",
    ...at(900, 740, 8),
    group: "hang",
    blurb: "Osu. Oxford Street's overgrown spot. Early drinks, mostly Accra.",
    actions: [sip("container-early", "Early drink", "Come before the street gets dressed.", 12), stroll("container-spot", "Lean on the spot", "You hear the evening plan itself.")],
  },
  {
    id: "epos",
    name: "Epo's",
    emoji: "🍻",
    ...at(900, 740, 9),
    group: "hang",
    blurb: "Osu. A mini carnival with a beer tower in the middle of it.",
    actions: [sip("epos-tower", "Share the tower", "The tower lands. Everybody suddenly has a glass.", 28), stroll("epos-carnival", "Walk the yard", "Speakers, smoke, and somebody you did not plan to see.")],
  },
  {
    id: "el-padrino",
    name: "El Padrino",
    emoji: "🚬",
    ...at(1580, 80, 1, 2),
    group: "hang",
    blurb: "Airport City. Bar, plates, and a cigar room inside Atlantic Tower.",
    actions: [sip("padrino-lounge", "Sit in the lounge", "Leather, low light, a bill with manners.", 40), plate("padrino-plate", "Order a plate", "You eat slowly because the room expects it.", 36)],
  },
  {
    id: "zen-garden",
    name: "Zen Garden",
    emoji: "🥁",
    ...at(1400, 620, 7),
    group: "hang",
    blurb: "Labone. Live highlife and palm-wine bands, shared wooden tables, dancing that starts in the chair.",
    actions: [dance("zen-band", "The band starts in highlife and the tables give up.", 35), plate("zen-table", "Share a table", "Somebody passes the kelewele without asking.", 16)],
  },
  {
    id: "polo-club",
    name: "Polo Club",
    emoji: "🐎",
    x: 1708,
    y: 80,
    group: "hang",
    blurb: "Airport Bypass. Restaurant and lounge looking onto the polo field.",
    actions: [stroll("polo-field", "Watch the field", "Horses, grass, and a drink you nurse.", 20), plate("polo-lunch", "Lunch on the lawn", "You sit up straighter than the afternoon requires.", 34)],
  },
  {
    id: "afrikiko",
    name: "Afrikiko",
    emoji: "🎺",
    x: 640,
    y: 420,
    group: "hang",
    blurb: "Ridge. Open air, a band, food, and dancing on the same patch of ground.",
    actions: [plate("afrikiko-chop", "Eat first", "You line the stomach before the horns come in.", 22), dance("afrikiko-band", "The band pulls the yard onto its feet.", 30)],
  },
  {
    id: "kempinski",
    name: "Kempinski lounge",
    emoji: "🏨",
    ...at(1580, 80, 2, 2),
    group: "hang",
    blurb: "Ridge. Hotel lounge. Diplomats, travellers, and Accra dressed for a quieter night.",
    actions: [sip("kempinski-lounge", "Sit in the lounge", "Soft chairs. Somebody is on a work call they should have ended.", 36)],
  },
  {
    id: "movenpick",
    name: "Mövenpick lounge",
    emoji: "🏨",
    ...at(1580, 80, 3, 2),
    group: "hang",
    blurb: "Airport City. A polished lounge for a night that stays seated.",
    actions: [sip("movenpick-lounge", "Order something still", "Ice, a short glass, the lobby humming.", 34)],
  },
  {
    id: "botanical",
    name: "Legon Botanical Gardens",
    emoji: "🌳",
    x: 1240,
    y: 120,
    group: "sea",
    blurb: "Legon. Canopy walk, high ropes, canoes, and a playground if you brought a child in your head.",
    actions: [stroll("botanical-canopy", "Canopy walk", "The city is a rumour under the leaves.", 15), stroll("botanical-canoe", "Take a canoe", "A short paddle and wet cuffs.", 20)],
  },
  {
    id: "kokrobite",
    name: "Kokrobite Beach",
    emoji: "🥁",
    x: 260,
    y: 1260,
    group: "sea",
    blurb: "Kokrobite. A fishing-village beach west of town. Drumming, and time that moves slower.",
    actions: [stroll("kokrobite-shore", "Sit with the village", "Boats, drums, and nobody checking a watch."), plate("kokrobite-grill", "Eat from a grill", "Fish, smoke, and a lime.", 18)],
  },
  {
    id: "jamestown",
    name: "Jamestown",
    emoji: "🎨",
    x: 160,
    y: 860,
    group: "hang",
    blurb: "Jamestown. The old neighbourhood. Paint, colonial walls, and the fishing beach at the end of the lane.",
    actions: [stroll("jamestown-lanes", "Walk the lanes", "You follow the colour and come out at the water."), stroll("jamestown-harbour", "Watch the boats", "Nets, shouts, and the sea doing its job.")],
  },
  {
    id: "chale-wote",
    name: "Chale Wote walls",
    emoji: "🖌️",
    x: 240,
    y: 820,
    group: "hang",
    blurb: "Jamestown. Festival murals that stay up after the crowd goes home.",
    actions: [stroll("chale-walls", "Read the walls", "Every alley kept a painting.")],
  },
  {
    id: "nkrumah",
    name: "Nkrumah Memorial Park",
    emoji: "🕊️",
    x: 300,
    y: 120,
    group: "civic",
    blurb: "Downtown. The first president's park, a museum, and grounds that ask you to slow down.",
    actions: [stroll("nkrumah-grounds", "Walk the grounds", "You read the stone and stand still for a minute.", 10), stroll("nkrumah-museum", "Step into the museum", "A quiet hour with the country's beginning.", 15)],
  },
  {
    id: "independence",
    name: "Independence Square",
    emoji: "⭐",
    x: 380,
    y: 180,
    group: "civic",
    blurb: "Downtown. The arch, the Black Star, and a square big enough to lose a thought in.",
    actions: [stroll("independence-arch", "Stand at the arch", "The star is the point. You let it be.")],
  },
  {
    id: "dubois",
    name: "Du Bois Centre",
    emoji: "📚",
    x: 460,
    y: 120,
    group: "civic",
    blurb: "Cantonments. The house and library of the scholar who made Ghana home.",
    actions: [stroll("dubois-house", "Walk the house", "Books, a grave, and a life that chose Accra.", 10)],
  },
  {
    id: "nubuke",
    name: "Nubuke Foundation",
    emoji: "🖼️",
    x: 700,
    y: 120,
    group: "hang",
    blurb: "East Legon. A room for new Ghanaian art, not a souvenir shop.",
    actions: [stroll("nubuke-show", "See the show", "You stand in front of one work longer than you planned.", 15)],
  },
  {
    id: "gallery-1957",
    name: "Gallery 1957",
    emoji: "🖼️",
    x: 780,
    y: 180,
    group: "hang",
    blurb: "Ridge. Inside the Kempinski. Emerging artists, white walls, a hush.",
    actions: [stroll("gallery-1957-walk", "Walk the rooms", "You leave with one image you cannot describe yet.", 15)],
  },
  {
    id: "artists-alliance",
    name: "Artists Alliance",
    emoji: "🖼️",
    x: 920,
    y: 240,
    group: "hang",
    blurb: "Labadi. Paintings, sculpture, and craft from people who have been at it for years.",
    actions: [stroll("alliance-floors", "Climb the floors", "Every landing has another Ghana.", 10)],
  },
  {
    id: "osu-night-market",
    name: "Osu Night Market",
    emoji: "🔥",
    ...at(900, 740, 10),
    group: "hang",
    blurb: "Osu. After dark the side lanes fill with charcoal, kelewele, khebab, and plantain.",
    actions: [plate("osu-grill", "Eat from the grill", "Kelewele, khebab, smoke in your shirt.", 14), stroll("osu-lanes", "Walk the lanes", "You follow the charcoal and lose Oxford Street.")],
  },
  {
    id: "sakumono",
    name: "Sakumono Lagoon",
    emoji: "🪶",
    x: 1860,
    y: 980,
    group: "sea",
    blurb: "Sakumono. A wetland at dusk. Herons, egrets, a boardwalk, no ticket.",
    actions: [stroll("sakumono-walk", "Walk the boardwalk", "Birds settle as the light goes. You do too.")],
  },
  {
    id: "auntie-muni",
    name: "Auntie Muni",
    emoji: "🍛",
    ...at(1400, 620, 8),
    group: "hang",
    blurb: "Labone. The waakye queue. Rice and beans, shito, wele, egg if you are lucky.",
    actions: [plate("muni-waakye", "Queue for waakye", "The line is the review. The plate ends the argument.", 14)],
  },
  {
    id: "asanka",
    name: "Asanka Local",
    emoji: "🍲",
    ...at(900, 740, 11),
    group: "hang",
    blurb: "Osu. Open-air chop bar. Banku and tilapia, fufu, red-red with plantain.",
    actions: [plate("asanka-banku", "Banku and tilapia", "Pepper, lime, and a fish that was grilled properly.", 22), plate("asanka-redred", "Red-red", "Beans, fried plantain, the stool is enough.", 16)],
  },
  {
    id: "jamestown-coffee",
    name: "Jamestown Coffee",
    emoji: "☕",
    x: 200,
    y: 760,
    group: "hang",
    blurb: "Nyaniba Estates. Strong coffee and a breakfast that arrives in a pan.",
    actions: [plate("jt-coffee-pan", "Breakfast in a pan", "Eggs, bread, and a cup that wakes the street in you.", 20), sip("jt-coffee-cup", "Just the coffee", "You sit with the cup and let the morning be small.", 10)],
  },
  {
    id: "kishitei",
    name: "Kishitei",
    emoji: "🍜",
    x: 1320,
    y: 700,
    group: "hang",
    blurb: "Osu. Noodles, a lighter plate, a good first stop if the night is still ahead.",
    actions: [plate("kishitei-bowl", "A bowl of noodles", "Steam, broth, and room left for later.", 24)],
  },
  {
    id: "dez-amis",
    name: "Café Dez Amis",
    emoji: "🥐",
    x: 1320,
    y: 760,
    group: "hang",
    blurb: "Osu side. Brunch, long lunch, sunset supper, and live music when Sunday feels like it.",
    actions: [plate("dez-brunch", "Stay for brunch", "The table turns into the afternoon.", 28), stroll("dez-sunday", "Sunday set", "Somebody plays while you finish the cup.")],
  },
  {
    id: "vine-brasa",
    name: "Vine and Brasa",
    emoji: "🍇",
    ...at(1400, 620, 9),
    group: "hang",
    blurb: "Labone. A table for local plates when you want the meal to feel like an evening.",
    actions: [plate("vine-plate", "Order the local plate", "You let the kitchen decide and you do not regret it.", 30)],
  },
];
