import type { ShopCategory, ShopItem, ShopKind } from "@/lib/game/world";

type Tier = "starter" | "mid" | "luxury";

type Spec = {
  name: string;
  tier?: Tier;
  kind?: ShopKind;
  stock?: boolean;
  job: string;
  price?: number;
  size?: string;
  where?: ShopItem["where"];
  unlock?: number;
};

const TIER_PRICE: Record<Tier, number> = { starter: 18, mid: 95, luxury: 480 };
const TIER_STARS: Record<Tier, number> = { starter: 1, mid: 3, luxury: 5 };
const SWATCH = ["#e7d7b8", "#3c8f4e", "#3d7ea6", "#c4563a", "#2c3338", "#c4a46a", "#f4f7fa"];
const ASSET = "Kenney Furniture Kit / Food Kit (kenney.nl). Poly Pizza search. Sketchfab low-poly. Mixamo for using it.";

function slug(room: string, name: string) {
  const body = name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 36);
  return `e-${room}-${body}`;
}

function rows(room: ShopCategory, items: Spec[]): ShopItem[] {
  return items.map((item, index) => {
    const tier = item.tier ?? "starter";
    const stock = item.stock ?? true;
    const where = item.where ?? (tier === "luxury" ? "boutique" : tier === "mid" ? "shop" : "market");
    const stars = TIER_STARS[tier];
    return {
      id: slug(room, item.name),
      name: item.name,
      price: item.price ?? TIER_PRICE[tier],
      detail: `${item.name}. Status ${stars}. Comfort ${stars * 2}. Colours: cream, green, blue, red. Size ${item.size ?? (stock ? "pack" : "1×1")}. Unlimited stock. ${where}.`,
      category: room,
      size: item.size ?? (stock ? "pack" : "1×1"),
      stars,
      color: SWATCH[(index + room.length) % SWATCH.length],
      kind: item.kind ?? (item.job === "food" ? "food" : "box"),
      stock,
      tier,
      job: item.job,
      where,
      pack: stock ? 1 : undefined,
      unlock: item.unlock,
      consume: false,
      asset: ASSET,
    };
  });
}

const p = (name: string, job: string, extra: Partial<Spec> = {}): Spec => ({ name, job, stock: true, ...extra });
const f = (name: string, job: string, kind: ShopKind, extra: Partial<Spec> = {}): Spec => ({ name, job, kind, stock: false, ...extra });

export const ESSENTIALS: ShopItem[] = [
  ...rows("kitchen", [
    p("Small cooking pot", "cook"),
    p("Medium cooking pot", "cook", { tier: "mid" }),
    p("Large cooking pot", "cook", { tier: "mid" }),
    p("Cooking pot set", "cook", { tier: "luxury", price: 220 }),
    p("Small frying pan", "cook"),
    p("Large frying pan", "cook", { tier: "mid" }),
    p("Non-stick frying pan", "cook", { tier: "mid" }),
    p("Saucepan", "cook"),
    p("Cooking spoon", "cook"),
    p("Ladle", "cook"),
    p("Spatula", "cook"),
    p("Knife set", "cook", { tier: "mid" }),
    p("Cutting board", "cook"),
    p("Grater", "cook"),
    p("Peeler", "cook"),
    p("Mortar and pestle", "cook", { tier: "mid" }),
    p("Asanka", "cook", { tier: "mid" }),
    p("Wooden spoon", "cook"),
    p("Stirring stick", "cook"),
    p("Colander", "cook"),
    p("Sieve", "cook"),
    p("Measuring cups", "cook"),
    p("Measuring spoons", "cook"),
    p("Mixing bowls", "cook"),
    p("Ceramic plates", "serve", { tier: "mid" }),
    p("Melamine plates", "serve"),
    p("Plastic plates", "serve"),
    p("Soup bowls", "serve"),
    p("Cereal bowls", "serve"),
    p("Serving bowls", "serve"),
    p("Cups", "serve"),
    p("Mugs", "serve"),
    p("Water glasses", "serve"),
    p("Wine glasses", "serve", { tier: "luxury" }),
    p("Beer glasses", "serve"),
    p("Juice glasses", "serve"),
    p("Cutlery set", "serve", { tier: "mid" }),
    p("Serving tray", "serve"),
    p("Small food containers", "store"),
    p("Medium food containers", "store"),
    p("Large food containers", "store"),
    f("Water filter", "water", "box", { tier: "mid", price: 160 }),
    p("Electric kettle", "cook", { tier: "mid" }),
    p("Stovetop kettle", "cook"),
    p("Thermos flask", "store"),
    f("Ice chest", "cool", "fridge", { tier: "mid", price: 140 }),
    p("Kitchen trash bin", "clean"),
    p("Dish rack", "clean"),
    p("Kitchen towels", "clean"),
    p("Apron", "cook"),
    p("Oven mitts", "cook"),
    p("Spice rack", "cook", { tier: "mid" }),
    p("Salt and pepper shakers", "cook"),
    p("Sugar bowl", "cook"),
    p("Tea strainer", "cook"),
    p("Bottle opener", "serve"),
    p("Can opener", "cook"),
    p("Corkscrew", "serve", { tier: "mid" }),
    p("Wooden chopping board", "cook"),
    p("Plastic chopping board", "cook"),
    p("Wash basin", "clean"),
    p("Cleaning bucket", "clean"),
    p("Water bucket", "water"),
    p("Jerry can", "water"),
  ]),
  ...rows("bath", [
    p("Bath bucket", "bathe"),
    p("Bowl and pitcher", "bathe"),
    p("Calabash dipper", "bathe"),
    f("Basic toilet", "bathe", "toilet", { tier: "starter", price: 160 }),
    f("Modern toilet", "bathe", "toilet", { tier: "mid", price: 340 }),
    f("Luxury toilet", "bathe", "toilet", { tier: "luxury", price: 980, unlock: 12 }),
    p("Toilet seat cover", "bathe"),
    p("Toilet brush", "clean"),
    p("Toilet paper holder", "bathe"),
    p("Toilet paper", "bathe"),
    f("Washbasin", "bathe", "sink", { tier: "mid", price: 180 }),
    p("Single tap", "water"),
    p("Double tap", "water", { tier: "mid" }),
    p("Mixer tap", "water", { tier: "luxury" }),
    f("Basic shower head", "bathe", "shower", { price: 70 }),
    f("Rain shower head", "bathe", "shower", { tier: "luxury", price: 420 }),
    f("Handheld shower", "bathe", "shower", { tier: "mid", price: 150 }),
    p("Shower curtain", "bathe"),
    p("Bath mat", "bathe"),
    p("Bath towel", "bathe"),
    p("Hand towel", "bathe"),
    p("Face towel", "bathe"),
    p("Towel rack", "bathe"),
    p("Soap dish", "bathe"),
    p("Bar soap", "bathe"),
    p("Liquid soap", "bathe"),
    p("Shampoo", "bathe"),
    p("Conditioner", "bathe"),
    p("Sponge", "bathe"),
    p("Loofah", "bathe"),
    f("Wall mirror", "groom", "curtain", { tier: "mid", price: 90 }),
    f("Mirror cabinet", "groom", "box", { tier: "luxury", price: 260 }),
    p("Toothbrush holder", "care"),
    p("Toothbrushes", "care"),
    p("Toothpaste", "care"),
    p("Comb", "groom"),
    p("Hairbrush", "groom"),
    p("Razor", "groom"),
    p("Bathroom slippers", "care"),
    p("Bathroom bin", "clean"),
    p("Plunger", "clean"),
    p("Drain cleaner", "clean"),
  ]),
  ...rows("sleep", [
    f("Single bed", "sleep", "bed", { price: 220, size: "1×2" }),
    f("Double bed", "sleep", "bed", { tier: "mid", price: 480, size: "2×1" }),
    f("Queen bed", "sleep", "bed", { tier: "luxury", price: 920, size: "2×2" }),
    f("King bed frame", "sleep", "bed", { tier: "luxury", price: 1400, size: "2×2", unlock: 10 }),
    f("Bunk bed", "sleep", "bed", { tier: "mid", price: 560, size: "1×2" }),
    f("Basic mattress", "sleep", "bed", { price: 140, size: "1×2" }),
    f("Spring mattress", "sleep", "bed", { tier: "mid", price: 360, size: "2×1" }),
    f("Foam mattress", "sleep", "bed", { tier: "mid", price: 240, size: "1×2" }),
    f("Memory mattress", "sleep", "bed", { tier: "luxury", price: 860, size: "2×2" }),
    f("Wood bed frame", "sleep", "bed", { tier: "mid", price: 300, size: "2×1" }),
    f("Metal bed frame", "sleep", "bed", { price: 180, size: "1×2" }),
    f("Upholstered bed frame", "sleep", "bed", { tier: "luxury", price: 1100, size: "2×2" }),
    p("Sleeping pillows", "sleep"),
    p("Decorative pillows", "sleep", { tier: "mid" }),
    p("Pillowcases", "sleep"),
    p("Plain bedsheets", "sleep"),
    p("Patterned bedsheets", "sleep", { tier: "mid" }),
    p("Duvet", "sleep", { tier: "mid" }),
    f("Mosquito net", "guard", "box", { price: 40 }),
    f("Bedside table", "sleep", "table", { tier: "mid", price: 120 }),
    f("Bedside lamp", "power", "lamp", { price: 55 }),
    f("Single wardrobe", "store", "box", { tier: "mid", price: 280, size: "1×1" }),
    f("Double wardrobe", "store", "box", { tier: "luxury", price: 640, size: "2×1" }),
    f("Walk-in wardrobe", "store", "box", { tier: "luxury", price: 1800, size: "2×2", unlock: 16 }),
    p("Clothes hangers", "store"),
    f("Chest of drawers", "store", "box", { tier: "mid", price: 240 }),
    f("Standing mirror", "groom", "curtain", { tier: "mid", price: 160 }),
    f("Full-length mirror", "groom", "curtain", { tier: "mid", price: 190 }),
    p("Basic curtains", "sleep"),
    p("Blackout curtains", "sleep", { tier: "mid" }),
    p("Silk curtains", "sleep", { tier: "luxury", price: 520 }),
    p("Blinds", "sleep", { tier: "mid" }),
    f("Bedroom rug", "sleep", "rug", { tier: "mid", price: 150, size: "2×2" }),
    f("Ceiling fan", "cool", "fan", { tier: "mid", price: 210 }),
    f("Standing fan", "cool", "fan", { tier: "mid", price: 160 }),
    f("Table fan", "cool", "fan", { price: 70 }),
    f("Window air conditioner", "cool", "ac", { tier: "luxury", price: 980 }),
    f("Split air conditioner", "cool", "ac", { tier: "luxury", price: 1400, unlock: 8 }),
    f("Rechargeable fan", "power", "fan", { tier: "mid", price: 180 }),
    p("Laundry basket", "wash"),
    p("Clothes line", "wash"),
    p("Drying rack", "wash"),
    p("Iron", "wash", { tier: "mid" }),
    p("Ironing board", "wash", { tier: "mid" }),
    p("Bed slippers", "care"),
    p("Under-bed storage boxes", "store"),
    p("Ear plugs", "sleep"),
    p("Eye mask", "sleep"),
    p("Robe", "sleep"),
    p("Bedside torch", "power"),
    p("Extra blanket", "sleep"),
    f("Night cooler", "cool", "fridge", { tier: "mid", price: 140 }),
  ]),
  ...rows("comfort", [
    f("2-seater sofa", "cool", "sofa", { tier: "mid", price: 340, size: "2×1" }),
    f("3-seater sofa", "cool", "sofa", { tier: "mid", price: 520, size: "3×1" }),
    f("L-shaped sofa", "cool", "sofa", { tier: "luxury", price: 1400, size: "3×2", unlock: 10 }),
    f("Armchair", "cool", "chair", { tier: "mid", price: 180 }),
    f("Coffee table", "serve", "table", { tier: "mid", price: 160 }),
    f("Side table", "serve", "table", { price: 70 }),
    f("TV stand", "cool", "table", { tier: "mid", price: 200 }),
    f("Basic TV", "cool", "tv", { tier: "mid", price: 480 }),
    f("Smart TV", "cool", "tv", { tier: "luxury", price: 1600 }),
    f("Large TV", "cool", "tv", { tier: "luxury", price: 2400, unlock: 12 }),
    p("TV antenna", "cool"),
    p("DStv decoder", "cool", { tier: "mid", price: 280 }),
    p("GOtv decoder", "cool", { tier: "mid", price: 160 }),
    f("Sound system", "cool", "box", { tier: "luxury", price: 760 }),
    f("Speakers", "cool", "box", { tier: "mid", price: 220 }),
    p("DVD player", "cool"),
    p("Living room curtains", "sleep"),
    f("Living room rug", "cool", "rug", { tier: "mid", price: 180, size: "2×2" }),
    p("Wall clock", "store"),
    p("Wall art", "faith"),
    p("Photo frames", "faith"),
    f("Real plant", "yard", "plant", { price: 40 }),
    f("Fake plant", "yard", "plant", { price: 25 }),
    p("Cushions", "sleep"),
    p("Throw pillows", "sleep"),
    p("Throw blanket", "sleep"),
    p("Centrepiece bowl", "serve"),
    f("Bookshelf", "desk", "box", { tier: "mid", price: 210 }),
    p("Magazine rack", "store"),
    f("Standing lamp", "power", "lamp", { tier: "mid", price: 90 }),
    f("Rechargeable lamp", "power", "lamp", { price: 65 }),
    f("Living room ceiling fan", "cool", "fan", { tier: "mid", price: 200 }),
    f("Living room standing fan", "cool", "fan", { tier: "mid", price: 170 }),
    f("Living room air conditioner", "cool", "ac", { tier: "luxury", price: 1500, unlock: 8 }),
    p("Ash tray", "clean"),
    p("Tissue box", "care"),
    p("Remote holder", "store"),
    p("Charging station", "power", { tier: "mid" }),
  ]),
  ...rows("dining", [
    f("2-seater dining table", "serve", "table", { tier: "mid", price: 180, size: "1×1" }),
    f("4-seater dining table", "serve", "table", { tier: "mid", price: 320, size: "2×2" }),
    f("6-seater dining table", "serve", "table", { tier: "luxury", price: 640, size: "2×2" }),
    f("8-seater dining table", "serve", "table", { tier: "luxury", price: 980, size: "3×2", unlock: 10 }),
    f("Dining chairs", "serve", "chair", { tier: "mid", price: 40 }),
    p("Tablecloth", "serve"),
    p("Place mats", "serve"),
    p("Napkins", "serve"),
    p("Napkin holder", "serve"),
    p("Dining centrepiece", "serve"),
    p("Serving dishes", "serve", { tier: "mid" }),
    p("Dining salt and pepper", "cook"),
    p("Water jug", "water"),
    f("Wine rack", "store", "box", { tier: "luxury", price: 260 }),
    f("Bar cart", "serve", "table", { tier: "luxury", price: 540, unlock: 12 }),
  ]),
  ...rows("laundry", [
    f("Top-load washing machine", "wash", "box", { tier: "luxury", price: 980 }),
    f("Front-load washing machine", "wash", "box", { tier: "luxury", price: 1400, unlock: 8 }),
    f("Dryer", "wash", "box", { tier: "luxury", price: 1200, unlock: 10 }),
    p("Laundry basket", "wash"),
    p("Washing powder", "wash"),
    p("Liquid detergent", "wash"),
    p("Fabric softener", "wash"),
    p("Bleach", "wash"),
    p("Stain remover", "wash"),
    p("Clothes line", "wash"),
    p("Clothes pegs", "wash"),
    p("Drying rack", "wash"),
    p("Iron", "wash", { tier: "mid" }),
    p("Ironing board", "wash", { tier: "mid" }),
    p("Starch spray", "wash"),
    p("Laundry bag", "wash"),
    f("Hand-wash sink", "wash", "sink", { tier: "mid", price: 150 }),
  ]),
  ...rows("clean", [
    p("Local broom", "clean"),
    p("Synthetic broom", "clean"),
    p("Mop", "clean"),
    p("Mop bucket", "clean"),
    p("Dustpan", "clean"),
    p("Dustbin with lid", "clean"),
    p("Dustbin liners", "clean"),
    p("Cleaning cloths", "clean"),
    p("Sponges", "clean"),
    p("Scrubbing brush", "clean"),
    p("Disinfectant", "clean"),
    p("Floor cleaner", "clean"),
    p("Glass cleaner", "clean"),
    p("Toilet cleaner", "clean"),
    p("Air freshener", "clean"),
    p("Insect spray", "guard"),
    p("Mosquito coil", "guard"),
    p("Mosquito repellent", "guard"),
    p("Rat trap", "guard"),
    p("Fly swatter", "guard"),
    f("Vacuum cleaner", "clean", "box", { tier: "luxury", price: 640, unlock: 8 }),
    p("Extra bucket", "clean"),
    p("Squeegee", "clean"),
    p("Feather duster", "clean"),
  ]),
  ...rows("store", [
    p("Small storage box", "store"),
    p("Medium storage box", "store"),
    p("Large storage box", "store", { tier: "mid" }),
    p("Metal trunk", "store", { tier: "mid" }),
    p("Plastic trunk", "store"),
    p("Suitcase", "store", { tier: "mid" }),
    p("Bolga basket", "store"),
    p("Local basket", "store"),
    p("Shoe rack", "store", { tier: "mid" }),
    p("Coat rack", "store"),
    p("Key holder", "store"),
    p("Wall hooks", "store"),
    p("Under-bed storage", "store"),
    p("Over-door storage", "store"),
    f("Garage shelves", "store", "box", { tier: "mid", price: 180 }),
    p("Storage jerry can", "water"),
  ]),
  ...rows("safe", [
    f("Fire extinguisher", "guard", "box", { tier: "mid", price: 120 }),
    f("Smoke detector", "guard", "box", { tier: "mid", price: 80 }),
    f("Carbon monoxide detector", "guard", "box", { tier: "mid", price: 90 }),
    p("First aid kit", "health"),
    p("Torch", "power"),
    f("Rechargeable emergency lamp", "power", "lamp", { price: 70 }),
    p("Candles", "power"),
    p("Matches", "power"),
    f("Rechargeable emergency fan", "power", "fan", { tier: "mid", price: 180 }),
    f("Small generator", "power", "box", { tier: "luxury", price: 850 }),
    f("Inverter", "power", "box", { tier: "luxury", price: 1600 }),
    f("Solar kit", "power", "box", { tier: "luxury", price: 3800, unlock: 12 }),
    f("Water storage tank", "water", "tank", { tier: "luxury", price: 700 }),
    f("Water pump", "water", "box", { tier: "mid", price: 320 }),
    p("Emergency jerry cans", "water"),
    p("Emergency contact card", "guard"),
    f("Home safe", "store", "vault", { tier: "luxury", price: 900, unlock: 8 }),
    f("Security camera", "guard", "box", { tier: "luxury", price: 420 }),
    f("Alarm system", "guard", "box", { tier: "luxury", price: 680, unlock: 10 }),
    p("Basic doorbell", "guard"),
    p("Video doorbell", "guard", { tier: "luxury", price: 360 }),
  ]),
  ...rows("care", [
    p("Bathing bucket", "bathe"),
    p("Bathing calabash", "bathe"),
    p("Bath soap", "bathe"),
    p("Bath sponge", "bathe"),
    p("Bath loofah", "bathe"),
    p("Bath shampoo", "bathe"),
    p("Bath conditioner", "bathe"),
    p("Body lotion", "care"),
    p("Deodorant", "care"),
    p("Perfume", "groom", { tier: "luxury", price: 180 }),
    p("Cologne", "groom", { tier: "mid" }),
    p("Care toothbrush", "care"),
    p("Care toothpaste", "care"),
    p("Mouthwash", "care"),
    p("Floss", "care"),
    p("Shaver", "groom"),
    p("Nail clipper", "groom"),
    p("Care comb", "groom"),
    p("Care hairbrush", "groom"),
    p("Hair oil", "groom"),
    p("Hair cream", "groom"),
    p("Hair gel", "groom"),
    p("Tissues", "care"),
    p("Care toilet paper", "care"),
    p("Sanitary pads", "care"),
    p("Cotton buds", "care"),
    p("Plasters", "health"),
    p("Bandages", "health"),
  ]),
  ...rows("pantry", [
    p("Rice container", "store", { tier: "mid" }),
    p("Beans container", "store"),
    p("Flour container", "store"),
    p("Pantry sugar bowl", "store"),
    p("Salt container", "store"),
    p("Palm oil bottle", "food"),
    p("Vegetable oil bottle", "food"),
    p("Spice containers", "cook"),
    p("Pepper grinder", "cook"),
    p("Onion basket", "store"),
    p("Garlic pot", "store"),
    p("Tomato crate", "food"),
    p("Yam basket", "store"),
    p("Plantain bunch hook", "store"),
    f("Kitchen fridge", "cool", "fridge", { tier: "luxury", price: 780 }),
    f("Chest freezer", "cool", "fridge", { tier: "luxury", price: 1100 }),
    f("Drinks cooler", "cool", "fridge", { tier: "mid", price: 160 }),
    f("Water dispenser", "water", "box", { tier: "mid", price: 280 }),
    p("Rice bag", "food"),
    p("Beans", "food"),
    p("Gari", "food"),
    p("Cassava flour", "food"),
    p("Corn dough", "food"),
    p("Yam", "food"),
    p("Plantain", "food"),
    p("Cassava", "food"),
    p("Tomatoes", "food"),
    p("Onions", "food"),
    p("Peppers", "food"),
    p("Cooking oil", "food"),
    p("Palm oil", "food"),
    p("Coconut oil", "food"),
    p("Salt", "food"),
    p("Sugar", "food"),
    p("Curry", "food"),
    p("Thyme", "food"),
    p("Pepper", "food"),
    p("Ginger", "food"),
    p("Garlic", "food"),
    p("Seasoning cubes", "food"),
    p("Shito", "food"),
    p("Tomato paste", "food"),
    p("Sardines", "food"),
    p("Corned beef", "food"),
    p("Bottled water", "water"),
    p("Soft drinks", "food"),
    p("Milo", "food"),
    p("Ovaltine", "food"),
    p("Bournvita", "food"),
    p("Tea bags", "food"),
    p("Coffee", "food"),
    p("Powdered milk", "food"),
    p("Cereal", "food"),
  ]),
  ...rows("power", [
    f("500L water tank", "water", "tank", { tier: "mid", price: 420, size: "yard" }),
    f("1000L water tank", "water", "tank", { tier: "luxury", price: 760, size: "yard" }),
    f("2000L water tank", "water", "tank", { tier: "luxury", price: 1200, size: "yard", unlock: 8 }),
    f("Compound water pump", "water", "box", { tier: "mid", price: 340, size: "yard" }),
    f("Borehole", "water", "box", { tier: "luxury", price: 4500, size: "yard", unlock: 20 }),
    f("Well", "water", "box", { tier: "mid", price: 800, size: "yard" }),
    p("Carrying jerry cans", "water"),
    p("Power bucket", "water"),
    p("Storage drum", "water", { tier: "mid" }),
    f("Small house generator", "power", "box", { tier: "luxury", price: 900, size: "yard" }),
    f("Medium generator", "power", "box", { tier: "luxury", price: 1800, size: "yard" }),
    f("Large generator", "power", "box", { tier: "luxury", price: 3200, size: "yard", unlock: 14 }),
    p("Petrol for the generator", "power"),
    p("Diesel for the generator", "power"),
    f("Inverter and battery", "power", "box", { tier: "luxury", price: 2100 }),
    f("Solar panels and battery", "power", "box", { tier: "luxury", price: 4600, unlock: 16 }),
    f("Power rechargeable lamp", "power", "lamp", { price: 60 }),
    f("Power rechargeable fan", "power", "fan", { tier: "mid", price: 190 }),
    p("Power candles", "power"),
    p("Power matches", "power"),
    p("Power torch", "power"),
    p("Power bank", "power"),
    p("Surge protector", "power", { tier: "mid" }),
  ]),
  ...rows("kids", [
    f("Crib", "kid", "bed", { tier: "mid", price: 260, size: "1×1" }),
    f("Baby cot", "kid", "bed", { tier: "mid", price: 300, size: "1×1" }),
    f("Changing table", "kid", "table", { tier: "mid", price: 180 }),
    f("High chair", "kid", "chair", { tier: "mid", price: 140 }),
    f("Playpen", "kid", "box", { tier: "mid", price: 200 }),
    p("Stroller", "kid", { tier: "mid" }),
    p("Baby monitor", "kid", { tier: "luxury", price: 220 }),
    p("Diaper bin", "clean"),
    p("Baby bottles", "kid"),
    p("Baby bathtub", "bathe"),
    f("Kids bed", "kid", "bed", { tier: "mid", price: 340, size: "1×2" }),
    f("Kids study desk", "desk", "desk", { tier: "mid", price: 160 }),
    p("School bag", "desk"),
    p("Children's books", "desk"),
    p("Toys", "kid"),
    f("Kids wardrobe", "store", "box", { tier: "mid", price: 240 }),
  ]),
  ...rows("skills", [
    f("Work desk", "desk", "desk", { tier: "mid", price: 280, size: "2×1" }),
    f("Office chair", "desk", "chair", { tier: "mid", price: 160 }),
    f("Filing cabinet", "store", "box", { tier: "mid", price: 190 }),
    p("Laptop stand", "desk"),
    f("Printer", "desk", "box", { tier: "luxury", price: 420 }),
    p("Pens and paper", "desk"),
    p("Notebooks", "desk"),
    f("Office bookshelf", "desk", "box", { tier: "mid", price: 200 }),
    f("Desk lamp", "power", "lamp", { price: 45 }),
    p("Pin board", "desk"),
    p("Whiteboard", "desk", { tier: "mid" }),
    p("Wall calendar", "desk"),
    f("Document safe", "store", "vault", { tier: "luxury", price: 700 }),
    p("Passport holder", "store"),
    p("Folder organisers", "store"),
  ]),
  ...rows("faith", [
    p("Bible", "faith"),
    p("Quran", "faith"),
    p("Prayer mat", "faith"),
    p("Rosary", "faith"),
    p("Cross", "faith"),
    p("Prayer corner cloth", "faith"),
    p("Incense", "faith"),
    p("Hymn book", "faith"),
    p("Family altar cloth", "faith"),
  ]),
  ...rows("health", [
    p("Home first aid kit", "health", { tier: "mid" }),
    p("Thermometer", "health"),
    p("Blood pressure monitor", "health", { tier: "mid" }),
    p("Weighing scale", "health"),
    f("Medicine cabinet", "health", "box", { tier: "mid", price: 120 }),
    p("Paracetamol", "health"),
    p("Malaria pack", "health", { tier: "mid" }),
    p("ORS sachets", "health"),
    p("Health mosquito repellent", "guard"),
    p("Multivitamins", "health"),
    p("Yoga mat", "fit"),
    p("Exercise mat", "fit"),
    p("Dumbbells", "fit", { tier: "mid" }),
    p("Skipping rope", "fit"),
    p("Reusable water bottle", "water"),
    f("Humidifier", "cool", "box", { tier: "luxury", price: 260 }),
    f("Air purifier", "cool", "box", { tier: "luxury", price: 480, unlock: 8 }),
  ]),
  ...rows("groom", [
    p("Hair clippers", "groom", { tier: "mid" }),
    p("Hair dryer", "groom", { tier: "mid" }),
    p("Hair straightener", "groom", { tier: "mid" }),
    p("Hair curler", "groom", { tier: "mid" }),
    p("Grooming hair cream", "groom"),
    p("Nail kit", "groom"),
    p("Makeup kit", "groom", { tier: "luxury", price: 160 }),
    f("Makeup mirror", "groom", "curtain", { tier: "mid", price: 90 }),
    p("Body spray", "groom"),
    p("Lotion", "care"),
    p("Cotton pads", "care"),
    p("Jewellery box", "store", { tier: "mid" }),
    p("Watch", "groom", { tier: "luxury", price: 240 }),
    p("Sunglasses", "groom", { tier: "mid" }),
    p("Wallet", "store"),
    p("Grooming key holder", "store"),
  ]),
  ...rows("pets", [
    p("Pet food bowl", "pet"),
    p("Pet water bowl", "pet"),
    p("Pet food bag", "pet"),
    f("Dog house", "pet", "box", { tier: "mid", price: 180, size: "yard" }),
    f("Dog bed", "pet", "box", { price: 60 }),
    f("Cat tower", "pet", "box", { tier: "mid", price: 140 }),
    p("Litter box", "pet"),
    p("Cat litter", "pet"),
    p("Leash", "pet"),
    p("Collar", "pet"),
    p("Pet toys", "pet"),
    p("Pet grooming kit", "pet"),
    p("Pet carrier", "pet", { tier: "mid" }),
    f("Bird cage", "pet", "box", { tier: "mid", price: 120 }),
    f("Fish tank", "pet", "tank", { tier: "luxury", price: 360 }),
  ]),
  ...rows("yard", [
    f("Manual gate", "guard", "box", { tier: "mid", price: 400, size: "yard" }),
    f("Sliding gate", "guard", "box", { tier: "luxury", price: 1200, size: "yard" }),
    f("Automatic gate", "guard", "box", { tier: "luxury", price: 2800, size: "yard", unlock: 14 }),
    f("Block fence", "guard", "wall", { tier: "luxury", price: 1600, size: "yard" }),
    f("Metal fence", "guard", "wall", { tier: "mid", price: 700, size: "yard" }),
    f("Wire fence", "guard", "wall", { price: 180, size: "yard" }),
    f("Compound wall", "guard", "wall", { tier: "luxury", price: 2000, size: "yard" }),
    f("Compound light", "power", "lamp", { tier: "mid", price: 80, size: "yard" }),
    f("Motion security light", "guard", "lamp", { tier: "mid", price: 110, size: "yard" }),
    f("Gatehouse", "guard", "box", { tier: "luxury", price: 2400, size: "yard", unlock: 16 }),
    f("Compound water tank", "water", "tank", { tier: "luxury", price: 800, size: "yard" }),
    f("Generator house", "power", "box", { tier: "mid", price: 500, size: "yard" }),
    p("Gravel", "yard"),
    p("Paving", "yard", { tier: "luxury", price: 600 }),
    p("Driveway", "yard", { tier: "luxury", price: 900 }),
    p("Rake", "yard"),
    p("Hoe", "yard"),
    p("Watering can", "yard"),
    p("Garden hose", "yard", { tier: "mid" }),
    f("Palm tree", "yard", "plant", { tier: "mid", price: 80, size: "yard" }),
    f("Shrub", "yard", "plant", { price: 25, size: "yard" }),
    p("Flower pots", "yard"),
    f("Outdoor chairs", "yard", "chair", { tier: "mid", price: 90 }),
    f("Compound bench", "yard", "chair", { tier: "mid", price: 120 }),
    p("Washing line posts", "wash"),
    p("Large compound dustbin", "clean"),
    f("Barbecue grill", "cook", "box", { tier: "mid", price: 220, size: "yard" }),
    f("Football goal", "kid", "box", { tier: "mid", price: 150, size: "yard" }),
    f("Basketball hoop", "kid", "box", { tier: "luxury", price: 280, size: "yard" }),
  ]),
  ...rows("motor", [
    p("Fuel jerry can", "motor"),
    p("Car wash kit", "motor"),
    p("Tyre pump", "motor"),
    p("Tool box", "motor", { tier: "mid" }),
    p("Jumper cables", "motor"),
    p("Spare tyre", "motor", { tier: "mid", price: 180 }),
    p("Car first aid kit", "health"),
    p("Car fire extinguisher", "guard"),
    p("Car cover", "motor", { tier: "mid" }),
    p("Car mats", "motor"),
    p("Car air freshener", "clean"),
  ]),
];

export const POWER_IDS = [
  "generator",
  "yellow-gen",
  "solar",
  "e-safe-small-generator",
  "e-power-small-house-generator",
  "e-power-medium-generator",
  "e-power-large-generator",
  "e-safe-inverter",
  "e-power-inverter-and-battery",
  "e-safe-solar-kit",
  "e-power-solar-panels-and-battery",
];

export function jobLine(job?: string) {
  switch (job) {
    case "cook":
      return "Cooks a meal from the cupboard.";
    case "serve":
      return "Feeds the table.";
    case "bathe":
      return "Washes you. Hygiene comes back.";
    case "sleep":
      return "A proper rest.";
    case "cool":
      return "Takes the heat out of the room when there is current.";
    case "power":
      return "Light and current when ECG goes.";
    case "water":
      return "Water in the house.";
    case "wash":
      return "Clothes come back clean in less time.";
    case "clean":
      return "The room stops smelling like yesterday.";
    case "store":
      return "Somewhere for the things that were on the floor.";
    case "guard":
      return "Keeps the night quieter. A net or coil cuts malaria.";
    case "care":
      return "Soap, teeth, the small things that keep you presentable.";
    case "food":
      return "A meal from the bag. Running out means you cook nothing.";
    case "faith":
      return "A quiet hour.";
    case "fit":
      return "A short workout at home.";
    case "health":
      return "Takes the edge off a sick day.";
    case "groom":
      return "You leave the house looking finished.";
    case "kid":
      return "The children have a place.";
    case "desk":
      return "Work that is not done on the bed.";
    case "pet":
      return "The animal eats, drinks, and stays.";
    case "yard":
      return "The compound looks kept.";
    case "motor":
      return "The car stays ready.";
    default:
      return "It earns its place in the house.";
  }
}
