import type { Spot, Verb } from "@/lib/game/world";

function act(partial: Partial<Verb> & Pick<Verb, "id" | "label" | "detail">): Verb {
  return { minutes: 25, cost: 0, earn: 0, effects: {}, ...partial };
}

function plate(id: string, label: string, detail: string, cost: number): Verb {
  return act({ id, label, detail, minutes: 25, cost, effects: { hunger: 20, fun: 6 }, tag: "food", emoji: "🍽️" });
}

export const FOOD_SPOTS: Spot[] = [
  {
    id: "accra-food-court",
    name: "Mall Food Court",
    emoji: "🍱",
    x: 1560,
    y: 900,
    group: "hang",
    blurb: "Teshie. Trays, numbers, and six kitchens behind one counter.",
    actions: [plate("food-court-order", "Order at the court", "Pick a stall. They call your number.", 35)],
  },
  {
    id: "osu-shawarma",
    name: "Oxford Shawarma",
    emoji: "🌯",
    x: 480,
    y: 400,
    group: "hang",
    blurb: "Osu. The wrap place that is still open when the clubs empty.",
    actions: [plate("shawarma-order", "Order a shawarma", "Chicken, beef, or both. Chips in the wrap.", 28)],
  },
  {
    id: "pizza-oven",
    name: "Spintex Pizza",
    emoji: "🍕",
    x: 1280,
    y: 980,
    group: "hang",
    blurb: "Spintex. A wood oven, a delivery bike, and a menu that fits on one page.",
    actions: [plate("pizza-order", "Order a pizza", "Chicken pizza is the one they make without asking.", 55)],
  },
  {
    id: "burger-joint",
    name: "Circle Burger",
    emoji: "🍔",
    x: 620,
    y: 640,
    group: "hang",
    blurb: "Kwame Nkrumah Circle. A counter, a grill, and fries in a paper boat.",
    actions: [plate("burger-order", "Order a burger", "Beef or chicken. The queue moves.", 32)],
  },
  {
    id: "fanice-parlour",
    name: "FanIce Parlour",
    emoji: "🍦",
    x: 900,
    y: 1040,
    group: "hang",
    blurb: "Labadi road. Cups, cones, and a freezer that hums.",
    actions: [plate("fanice-order", "Get a cup", "One scoop, then the argument about a second.", 8)],
  },
  {
    id: "morning-coffee",
    name: "Morning Coffee",
    emoji: "☕",
    x: 1100,
    y: 360,
    group: "hang",
    blurb: "Airport City. Opens with the offices. Oats, eggs, and a queue for the good machine.",
    actions: [plate("coffee-order", "Order coffee", "Breakfast only feels right before noon.", 15)],
  },
  {
    id: "circle-night-food",
    name: "Circle Night Bites",
    emoji: "🔥",
    x: 700,
    y: 560,
    group: "hang",
    blurb: "Circle. Open when the trotros thin out. Kebab, gizzard, and a coal pot.",
    actions: [plate("late-order", "Order a late plate", "The grill is the only light on this corner.", 15)],
  },
  {
    id: "oxford-street-food",
    name: "Oxford Street Food",
    emoji: "🍌",
    x: 420,
    y: 560,
    group: "hang",
    blurb: "Osu. Hawkers along the pavement. Kelewele, pies, and pure water.",
    actions: [plate("street-order", "Buy from a hawker", "The price is shouted. You can still talk it down.", 8)],
  },
  {
    id: "mall-super",
    name: "Mall Supermarket",
    emoji: "🛒",
    x: 1680,
    y: 760,
    group: "hang",
    blurb: "Teshie. Aisles, a cold room, and a till that prints a long receipt.",
    actions: [act({ id: "super-run", label: "Fill a basket", detail: "Rice, milk, and the thing you came for.", minutes: 30, cost: 80, effects: { fun: 4 }, emoji: "🛒" })],
  },
  {
    id: "circle-bakery",
    name: "Circle Bakery",
    emoji: "🍞",
    x: 540,
    y: 700,
    group: "hang",
    blurb: "Circle. Bread before dawn, meat pies by nine, the good doughnuts gone by noon.",
    actions: [plate("bakery-order", "Buy from the case", "Pie, chin chin, or a loaf still warm.", 8)],
  },
  {
    id: "osu-pharmacy",
    name: "Osu Pharmacy",
    emoji: "💊",
    x: 360,
    y: 500,
    group: "work",
    blurb: "Osu. A counter, a pharmacist, and the medicine the clinic wrote down.",
    actions: [act({ id: "pharmacy-buy", label: "Buy medicine", detail: "You read the box twice. They explain the dose.", minutes: 15, cost: 18, effects: { energy: 6 }, emoji: "💊" })],
  },
  {
    id: "spintex-fuel",
    name: "Spintex Fuel",
    emoji: "⛽",
    x: 1360,
    y: 900,
    group: "work",
    blurb: "Spintex. Pumps, a mini-mart, and a car wash around the side.",
    actions: [
      act({ id: "fuel-fill", label: "Fill the tank", detail: "The attendant asks how much.", minutes: 12, cost: 40, effects: { fun: 2 }, emoji: "⛽" }),
      act({ id: "fuel-wash", label: "Wash the car", detail: "Soap, a hose, and a boy who wants the tip.", minutes: 25, cost: 20, effects: { fun: 4 }, emoji: "🧽" }),
    ],
  },
  {
    id: "trasacco-gate",
    name: "Trasacco Gate",
    emoji: "🏡",
    x: 1480,
    y: 180,
    group: "home",
    blurb: "East Legon. A gated estate. Wide streets, guards, and houses that cost a fortune.",
    actions: [
      act({
        id: "trasacco-enter",
        label: "Speak to the guard",
        detail: "They check the log. Residents drive in. Everyone else states who they came to see.",
        minutes: 8,
        effects: { social: 4 },
        emoji: "🛂",
      }),
    ],
  },
  {
    id: "passport-office",
    name: "Passport Office",
    emoji: "🛂",
    x: 1180,
    y: 260,
    group: "civic",
    blurb: "Ridge. Forms, a number, and a photograph that must look like you.",
    actions: [act({ id: "passport-form", label: "Take a number", detail: "The clerk wants the form filled before you reach the desk.", minutes: 40, cost: 20, effects: { energy: -4 }, emoji: "📄" })],
  },
  {
    id: "dvla-office",
    name: "DVLA",
    emoji: "🪪",
    x: 1240,
    y: 420,
    group: "civic",
    blurb: "The licence office. An eye test, a queue, and a plastic card at the end.",
    actions: [act({ id: "dvla-queue", label: "Join the licence queue", detail: "Bring the papers. The photo booth is in the corner.", minutes: 50, cost: 30, effects: { energy: -4 }, emoji: "🪪" })],
  },
  {
    id: "adum-shawarma",
    name: "Adum Shawarma",
    emoji: "🌯",
    x: 820,
    y: 560,
    group: "hang",
    town: "kumasi",
    blurb: "Adum. A Kumasi wrap, hotter pepper, same queue.",
    actions: [plate("adum-shawarma-order", "Order a shawarma", "They ask chicken or beef before you finish hello.", 24)],
  },
  {
    id: "asokwa-bakery",
    name: "Asokwa Bakery",
    emoji: "🍞",
    x: 900,
    y: 800,
    group: "hang",
    town: "kumasi",
    blurb: "Asokwa. Sugar bread and meat pies for the morning trotro.",
    actions: [plate("asokwa-bakery-order", "Buy bread", "The loaf is warm. The pie is gone if you are late.", 6)],
  },
  {
    id: "kejetia-night",
    name: "Kejetia Night Grill",
    emoji: "🔥",
    x: 860,
    y: 500,
    group: "hang",
    town: "kumasi",
    blurb: "Kejetia after dark. Gizzard, koko for the early ones, and a coal pot that does not sleep.",
    actions: [plate("kejetia-night-order", "Order from the grill", "Late food. The pepper is not a suggestion.", 12)],
  },
];

export const SPOT_HOURS: Record<string, { hours: string; open: [number, number] }> = {
  "circle-night-food": { hours: "2:00 – 5:00", open: [2, 5] },
  "kejetia-night": { hours: "2:00 – 5:00", open: [2, 5] },
  "morning-coffee": { hours: "5:00 – 11:00", open: [5, 11] },
  "osu-shawarma": { hours: "12:00 – 3:00", open: [12, 27] },
  "adum-shawarma": { hours: "12:00 – 3:00", open: [12, 27] },
  "mini-mart": { hours: "Open all night", open: [0, 24] },
  "kejetia-mart": { hours: "Open all night", open: [0, 24] },
};

function visit(id: string, label: string, detail: string, cost = 0, effects: Verb["effects"] = { fun: 4, social: 2 }): Verb {
  return act({ id, label, detail, minutes: 20, cost, effects });
}

export const CITY_SPOTS: Spot[] = [
  { id: "farmers-market", name: "Farmers Market", emoji: "🥬", x: 1860, y: 160, group: "hang", blurb: "Saturday morning. Tomatoes, garden eggs, and a price you can still talk down.", actions: [visit("farmers-buy", "Buy the week's pot", "You leave with peppers, plantain, and a story from the woman who grew them.", 25, { fun: 6, social: 6 })] },
  { id: "tema-fish-market", name: "Tema Fish Market", emoji: "🐟", x: 1860, y: 280, group: "hang", blurb: "The coast. Ice, scales, and tilapia that was swimming this morning.", actions: [visit("fish-buy", "Buy fish", "You point. They clean it. The pepper is your problem at home.", 30, { fun: 4, social: 4 })] },
  { id: "accra-meat-market", name: "Meat Market", emoji: "🥩", x: 1860, y: 400, group: "hang", blurb: "A butcher's lane. Goat, beef, and a knife that does not hesitate.", actions: [visit("meat-buy", "Buy meat", "They ask how many people you are feeding.", 35, { fun: 2, social: 4 })] },
  { id: "mini-mart", name: "Mini-Mart", emoji: "🏪", x: 1860, y: 520, group: "hang", blurb: "Open when everything else has locked the shutter. Water, bread, credit.", actions: [visit("mart-buy", "Grab something", "The fridge light is the brightest thing on the road.", 8, { fun: 2 })] },
  { id: "hardware-yard", name: "Hardware Yard", emoji: "🔩", x: 1860, y: 640, group: "work", blurb: "Cement, nails, and a man who knows which pipe you actually need.", actions: [visit("hardware-buy", "Buy supplies", "You came for one thing. You leave with three.", 40, { fun: 2 })] },
  { id: "furniture-hall", name: "Furniture Hall", emoji: "🛋️", x: 1860, y: 760, group: "hang", blurb: "Sofas in a row, a price on each tag, and a van if you mean it.", actions: [visit("furniture-look", "Walk the showroom", "You sit on one sofa longer than you need to.", 0, { fun: 6 })] },
  { id: "car-showroom", name: "Car Showroom", emoji: "🚗", x: 1860, y: 880, group: "work", blurb: "New metal, a cold floor, and a salesperson who already knows your budget.", actions: [visit("showroom-look", "Look at the cars", "You sit in one. The price is on the windscreen.", 0, { fun: 8 })] },
  { id: "okada-hub", name: "Okada Hub", emoji: "🏍️", x: 1860, y: 1000, group: "hang", blurb: "Helmets on the handlebars. They know the shortcuts.", actions: [visit("okada-ask", "Ask the riders", "Somebody offers the fare before you finish the question.", 0, { social: 6 })] },
  { id: "osu-car-wash", name: "Car Wash", emoji: "🧽", x: 1860, y: 1120, group: "work", blurb: "Soap, a hose, and a queue of cars that want to look new.", actions: [visit("wash-bay", "Wash the car", "They do the wheels last. The tip is not on the sign.", 20, { fun: 4 })] },
  { id: "laundry-house", name: "Laundromat", emoji: "👕", x: 1860, y: 1240, group: "work", blurb: "Machines, tokens, and a bench for the wait.", actions: [visit("laundry-run", "Wash a load", "You sit with the spin cycle. The shirt survives.", 15, { hygiene: 8, fun: 2 })] },
  { id: "dry-clean", name: "Dry Cleaners", emoji: "🧥", x: 80, y: 200, group: "work", blurb: "The good shirt, the wedding cloth, the thing you cannot wash at home.", actions: [visit("dry-drop", "Drop a garment", "They write your name on the ticket. Thursday.", 25, { fun: 2, hygiene: 4 })] },
  { id: "shoe-fix", name: "Shoe Repair", emoji: "👞", x: 80, y: 320, group: "work", blurb: "A stool, a hammer, and a sole that has another month in it.", actions: [visit("shoe-mend", "Mend the shoes", "He matches the colour better than you expected.", 12, { fun: 2 })] },
  { id: "pet-shop", name: "Pet Shop", emoji: "🐕", x: 80, y: 440, group: "hang", blurb: "Birds, feed, and a puppy the whole shop is negotiating.", actions: [visit("pet-look", "Look at the animals", "You leave with feed, or with a reason to come back.", 10, { fun: 8 })] },
  { id: "plant-nursery", name: "Plant Nursery", emoji: "🌿", x: 80, y: 560, group: "hang", blurb: "Trees in bags, and a gardener who talks to them.", actions: [visit("nursery-buy", "Buy a plant", "It will live if you water it. He tells you how.", 20, { fun: 6 })] },
  { id: "builders-yard", name: "Builders Yard", emoji: "🧱", x: 80, y: 680, group: "work", blurb: "Blocks, sand, and the crew that can start on Monday.", actions: [visit("builders-ask", "Price a load", "They ask where the plot is before they say a number.", 0, { social: 4 })] },
  { id: "casino-floor", name: "Casino", emoji: "🎰", x: 80, y: 800, group: "hang", blurb: "High-end. The Bet app on your phone is the same money, with better lights.", actions: [visit("casino-floor-walk", "Walk the floor", "You do not have to play. The room still spends your evening.", 0, { fun: 8, social: 4 })] },
  { id: "karaoke-box", name: "Karaoke Bar", emoji: "🎤", x: 80, y: 920, group: "hang", blurb: "A book of songs, a microphone, and friends who will not let you sit.", actions: [visit("karaoke-sing", "Take a song", "Highlife, then something you only know the chorus of.", 15, { fun: 14, social: 10, energy: -4 })] },
  { id: "shisha-room", name: "Shisha Lounge", emoji: "💨", x: 80, y: 1040, group: "hang", blurb: "Low seats, fruit tobacco, and a night that refuses to hurry.", actions: [visit("shisha-sit", "Take a seat", "They bring the coal. The conversation does the rest.", 30, { fun: 8, social: 8, energy: -2 })] },
  { id: "cigar-lounge", name: "Cigar Lounge", emoji: "🥃", x: 80, y: 1160, group: "hang", blurb: "Leather, a humidor, and a bill that assumes you belong.", actions: [visit("cigar-sit", "Sit with a whisky", "The room is quiet on purpose.", 50, { fun: 8, social: 4 })] },
  { id: "spa-house", name: "Spa", emoji: "💆", x: 80, y: 1280, group: "hang", blurb: "Massage, a facial, and an hour where nobody needs you.", actions: [visit("spa-book", "Book a treatment", "You come out slower than you went in.", 80, { fun: 12, hygiene: 10, energy: 8 })] },
  { id: "tattoo-ink", name: "Tattoo Parlour", emoji: "🖋️", x: 200, y: 1280, group: "hang", blurb: "A chair, a stencil, and a conversation about how much it will hurt.", actions: [visit("tattoo-consult", "Talk about a tattoo", "You look at the book. You do not have to decide today.", 0, { fun: 4, social: 4 })] },
  { id: "nail-bar", name: "Nail Bar", emoji: "💅", x: 320, y: 1280, group: "hang", blurb: "Colour on a wheel, and a chair that takes an hour.", actions: [visit("nails-set", "Get a set", "You pick a colour. They pick the shape.", 40, { fun: 8, hygiene: 4 })] },
  { id: "braid-house", name: "Braid House", emoji: "💇", x: 440, y: 1280, group: "hang", blurb: "Braids, weave, extensions. The chair knows how long this takes.", actions: [visit("braid-sit", "Sit for hair", "They ask the style before they touch your head.", 60, { fun: 8, social: 6, hygiene: 6 })] },
  { id: "dental-clinic", name: "Dental Clinic", emoji: "🦷", x: 200, y: 160, group: "work", blurb: "A chair, a light, and a bill that arrives after the numbness.", actions: [visit("dental-check", "Get a checkup", "They count what hurts. You leave with a date to come back.", 50, { energy: -4, hygiene: 6 })] },
  { id: "eye-clinic", name: "Eye Clinic", emoji: "👓", x: 200, y: 280, group: "work", blurb: "Charts on the wall, and frames in a glass case.", actions: [visit("eye-test", "Test your eyes", "You read the small line. They write the numbers down.", 40, { energy: -2 })] },
  { id: "vet-clinic", name: "Vet Clinic", emoji: "🐾", x: 200, y: 400, group: "work", blurb: "For the dog, the cat, or the bird that stopped singing.", actions: [visit("vet-visit", "See the vet", "They are gentle. The animal is not convinced.", 45, { fun: 4, social: 2 })] },
  { id: "pet-groom", name: "Pet Groomer", emoji: "✂️", x: 200, y: 520, group: "hang", blurb: "A bath, a clip, and a bow the dog did not ask for.", actions: [visit("groom-book", "Book a groom", "You wait with the other owners. The dog comes out proud.", 30, { fun: 6 })] },
  { id: "estate-agent", name: "Estate Agent", emoji: "🏘️", x: 200, y: 640, group: "work", blurb: "Plots, leases, and the Trasacco folder they only open if you ask.", actions: [visit("agent-sit", "Ask about land", "They show East Legon first. Trasacco is the last page.", 0, { social: 4, fun: 2 })] },
  { id: "law-office", name: "Law Office", emoji: "⚖️", x: 200, y: 760, group: "work", blurb: "Not the court. The room where the papers get written.", actions: [visit("lawyer-consult", "Consult a lawyer", "They listen, then they tell you what it will cost.", 80, { social: 2, energy: -2 })] },
  { id: "accounts-firm", name: "Accounts Firm", emoji: "📒", x: 200, y: 880, group: "work", blurb: "Books, tax, and a calendar that knows when the year ends.", actions: [visit("accounts-sit", "Sit with the books", "They find the number you were avoiding.", 40, { energy: -2 })] },
  { id: "insurance-desk", name: "Insurance Office", emoji: "📄", x: 200, y: 1000, group: "work", blurb: "A policy for the car, the shop, or the house you have not finished.", actions: [visit("insurance-ask", "Ask for a quote", "They want the year of the car before they smile.", 0, { social: 2 })] },
  { id: "immigration-desk", name: "Immigration", emoji: "🛂", x: 200, y: 1120, group: "civic", blurb: "Permits, stamps, and a number you will hold for a while.", actions: [visit("immigration-number", "Take a number", "The clerk wants the form before the conversation.", 20, { energy: -4 })] },
  { id: "traffic-police", name: "Traffic Police", emoji: "🚦", x: 320, y: 160, group: "civic", blurb: "The station for the road. Documents, a lecture, or a fine.", actions: [visit("traffic-desk", "Ask at the desk", "They want the papers in the order they expect.", 0, { energy: -2 })] },
  { id: "fire-station", name: "Fire Station", emoji: "🚒", x: 320, y: 280, group: "civic", blurb: "An engine in the bay, and a crew that hopes the night stays quiet.", actions: [visit("fire-visit", "Visit the bay", "They show you the engine. You do not touch the hose.", 0, { fun: 4, social: 4 })] },
  { id: "burma-barracks", name: "Burma Camp", emoji: "🎖️", x: 320, y: 400, group: "civic", blurb: "Military barracks. The gate is not a suggestion.", actions: [visit("barracks-gate", "Approach the gate", "The sentry checks your name and sends you back to the road.", 0, { energy: -2 })] },
  { id: "parliament-house", name: "Parliament", emoji: "🏛️", x: 320, y: 520, group: "civic", blurb: "The house on the hill. Sitting days are not visiting days.", actions: [visit("parliament-gate", "Walk up to the gate", "Security turns you around. The flag still moves.", 0, { fun: 2 })] },
  { id: "jubilee-gate", name: "Jubilee House", emoji: "🇬🇭", x: 320, y: 640, group: "civic", blurb: "The presidency. You can see the walls. You cannot see the rooms.", actions: [visit("jubilee-look", "Look from the road", "The guard nods. That is the whole visit.", 0, { fun: 2 })] },
  { id: "embassy-gate", name: "Embassy Row", emoji: "🌐", x: 320, y: 760, group: "civic", blurb: "Flags, a queue, and a window that closes on time.", actions: [visit("embassy-window", "Ask at the window", "They take the question and point you to the website.", 0, { energy: -2 })] },
  { id: "accra-zoo", name: "Accra Zoo", emoji: "🦁", x: 320, y: 880, group: "sea", blurb: "A small zoo. Shade, a map, and animals that have heard every joke.", actions: [visit("zoo-walk", "Walk the grounds", "You stay longer at one cage than you planned.", 20, { fun: 12, energy: -4 })] },
  { id: "botanical-gate", name: "Botanical Gardens", emoji: "🌳", x: 320, y: 1000, group: "sea", blurb: "Legon. Wide paths, labelled trees, and a quiet that Accra rarely allows.", actions: [visit("garden-walk", "Walk the paths", "You read three labels and then you just walk.", 10, { fun: 10, energy: 4 })] },
  { id: "public-library", name: "Public Library", emoji: "📚", x: 320, y: 1120, group: "civic", blurb: "Fans, tables, and a silence people actually keep.", actions: [visit("library-read", "Read for a while", "You take a chair by the window. An hour disappears.", 0, { fun: 6, energy: 2 })] },
  { id: "accra-museum", name: "National Museum", emoji: "🏺", x: 440, y: 160, group: "civic", blurb: "Stools, cloth, and the long story of how this country got here.", actions: [visit("museum-tour", "Walk the galleries", "The guide knows which room people skip. You do not skip it.", 20, { fun: 10, social: 4 })] },
  { id: "kejetia-mart", name: "Kejetia Mini-Mart", emoji: "🏪", x: 980, y: 700, group: "hang", town: "kumasi", blurb: "Open all night. Water, bread, and a fan that works.", actions: [visit("kejetia-mart-buy", "Buy a small thing", "Kumasi prices. The bread is still warm.", 6, { fun: 2 })] },
  { id: "kumasi-meat-market", name: "Kumasi Meat Market", emoji: "🥩", x: 700, y: 860, group: "hang", town: "kumasi", blurb: "Asokwa side. The butcher knows the regulars by their order.", actions: [visit("kumasi-meat-buy", "Buy meat", "Cheaper than Accra. The pepper is not.", 28, { fun: 2, social: 4 })] },
  { id: "kumasi-farmers-market", name: "Kumasi Farmers Market", emoji: "🥬", x: 1040, y: 860, group: "hang", town: "kumasi", blurb: "Weekly. Garden eggs, kontomire, and yam from outside town.", actions: [visit("kumasi-farmers-buy", "Fill a basket", "The woman adds a pepper you did not pay for.", 18, { fun: 6, social: 6 })] },
];

