import type { Spot, Verb } from "@/lib/game/world";

function act(partial: Partial<Verb> & Pick<Verb, "id" | "label" | "detail">): Verb {
  return { minutes: 40, cost: 0, earn: 0, effects: {}, ...partial };
}

const plate = (id: string, label: string, detail: string, cost: number, hunger = 36): Verb =>
  act({ id, label, detail, minutes: 40, cost, effects: { hunger, fun: 8, social: 6 }, tag: "food", social: true });

export const KUMASI_SPOTS: Spot[] = [
  {
    id: "kejetia",
    name: "Kejetia Market",
    emoji: "🧺",
    x: 780,
    y: 620,
    group: "hang",
    town: "kumasi",
    blurb: "Adum. The biggest market in West Africa. Lanes, cloth, and a price that moves if you look tired.",
    actions: [
      act({ id: "kejetia-walk", label: "Walk the lanes", detail: "You lose the entrance and find a better price two turns later.", minutes: 70, cost: 15, effects: { fun: 18, social: 12, energy: -10, hygiene: -6 }, emoji: "🧺" }),
      plate("kejetia-koko", "Koko and koose", "Morning porridge and bean cakes before the lanes fill.", 8, 28),
    ],
  },
  {
    id: "kumasi-central",
    name: "Kumasi Central Market",
    emoji: "🧵",
    x: 700,
    y: 740,
    group: "hang",
    town: "kumasi",
    blurb: "Adum. The older market beside Kejetia. Second-hand shoes and bolts of cloth.",
    actions: [
      act({ id: "central-cloth", label: "Buy cloth", detail: "The seller snaps the fabric so you hear the quality.", minutes: 40, cost: 60, effects: { fun: 12, social: 8 }, emoji: "🧵" }),
      plate("central-rice", "Rice and stew at the stall", "A plastic chair and a plate that arrives fast.", 12, 34),
    ],
  },
  {
    id: "manhyia",
    name: "Manhyia Palace",
    emoji: "👑",
    x: 1120,
    y: 380,
    group: "civic",
    town: "kumasi",
    blurb: "Manhyia. Gold weights, stools, and the museum of the Asantehene.",
    actions: [
      act({ id: "manhyia-museum", label: "Tour the museum", detail: "You read the stools twice. The guide does not hurry you.", minutes: 80, cost: 40, effects: { fun: 16, social: 10, energy: -6 }, skill: "charm", emoji: "👑" }),
      act({ id: "manhyia-yard", label: "Stand in the palace yard", detail: "On Akwasidae the drums start before you are ready.", minutes: 40, effects: { fun: 14, social: 12 }, emoji: "🥁" }),
    ],
  },
  {
    id: "baba-yara",
    name: "Baba Yara Stadium",
    emoji: "🏟️",
    x: 440,
    y: 380,
    group: "hang",
    town: "kumasi",
    blurb: "Bantama. Baba Yara. Asante Kotoko, horns, and a stand that stands up together.",
    actions: [
      act({ id: "baba-match", label: "Watch Kotoko", detail: "The anthem, then the argument, then a goal.", minutes: 110, cost: 25, effects: { fun: 30, social: 16, hunger: -8 }, social: true, emoji: "🏟️" }),
      act({ id: "baba-jog", label: "Jog the empty stands", detail: "No match today. Just the concrete and your own pace.", minutes: 30, effects: { energy: -10, hygiene: -8, fun: 6 }, skill: "fitness", tag: "gym", emoji: "🏃" }),
    ],
  },
  {
    id: "knust",
    name: "KNUST",
    emoji: "🎓",
    x: 1460,
    y: 250,
    group: "work",
    town: "kumasi",
    blurb: "KNUST. The campus sits in trees. Tech junction feeds everyone who is late for a lecture.",
    actions: [
      act({ id: "knust-walk", label: "Walk the campus", detail: "Neem trees, a faculty you cannot name, and students in a hurry.", minutes: 50, effects: { fun: 12, energy: -6, social: 8 }, emoji: "🌳" }),
      act({ id: "knust-library", label: "Sit in the library", detail: "Cold air, whispering, and a desk by the window.", minutes: 70, effects: { fun: 8, energy: -4, social: 4 }, skill: "career", emoji: "📚" }),
      act({ id: "knust-lecture", label: "Slip into a lecture", detail: "You are not registered. The back row does not ask.", minutes: 55, effects: { fun: 10, social: 6 }, emoji: "🎓" }),
      plate("knust-canteen", "Canteen jollof", "Student price. The queue moves when it wants to.", 12, 34),
    ],
  },
  {
    id: "bosomtwe",
    name: "Lake Bosomtwe",
    emoji: "🌊",
    x: 400,
    y: 1100,
    group: "sea",
    town: "kumasi",
    blurb: "Lake Road. A crater lake outside Kumasi. The water is still and the tilapia is not.",
    actions: [
      act({ id: "bosomtwe-shore", label: "Sit on the shore", detail: "No tide. Just the bowl of the lake and a long afternoon.", minutes: 70, effects: { fun: 22, energy: 6, social: 6 }, emoji: "🌊" }),
      plate("bosomtwe-fish", "Grilled tilapia", "Pepper, banku, and a view of the crater.", 30, 42),
    ],
  },
  {
    id: "adum-night",
    name: "Adum night",
    emoji: "🎶",
    x: 900,
    y: 520,
    group: "hang",
    town: "kumasi",
    blurb: "Prempeh II after dark. Highlife first, then the speakers get rude.",
    actions: [
      act({ id: "adum-club", label: "Stay for the set", detail: "A small floor, a big speaker, and somebody who knows your cousin.", minutes: 120, cost: 40, effects: { fun: 28, social: 16, energy: -14, hygiene: -8 }, tag: "party", skill: "music", emoji: "🎶" }),
      plate("adum-suya", "Night suya", "Smoke, pepper, and a toothpick.", 18, 24),
    ],
  },
  {
    id: "fufu-joint",
    name: "Asafo fufu joint",
    emoji: "🍲",
    x: 620,
    y: 500,
    group: "hang",
    town: "kumasi",
    blurb: "Asafo. Fufu pounded in the yard. Light soup that means it.",
    actions: [
      plate("asafo-fufu", "Fufu and light soup", "Goat, a ball of fufu, and a bench you will not leave quickly.", 28, 50),
      act({ id: "asafo-pound", label: "Help pound", detail: "They hand you the pestle. Your arms file a complaint.", minutes: 25, effects: { social: 14, energy: -12, fun: 8 }, skill: "cooking", emoji: "🥁" }),
    ],
  },
  {
    id: "kumasi-airport",
    name: "Kumasi Airport",
    emoji: "✈️",
    x: 1700,
    y: 280,
    group: "work",
    town: "kumasi",
    blurb: "A short terminal. Passion Airways back to Kotoka, and a taxi rank that already knows your bag.",
    actions: [
      act({ id: "kumasi-planes", label: "Watch the apron", detail: "One jet, a lot of sky, and somebody waving at a cousin.", minutes: 30, effects: { fun: 10, social: 6 }, emoji: "✈️" }),
      plate("kumasi-snack", "Terminal meat pie", "Hot, flaky, gone before boarding.", 15, 18),
    ],
  },
  {
    id: "bonwire-stall",
    name: "Bonwire kente stall",
    emoji: "🟨",
    x: 980,
    y: 700,
    group: "hang",
    town: "kumasi",
    blurb: "Adum. A stall that sells Bonwire strips. The cloth is heavier than the bag.",
    actions: [
      act({ id: "bonwire-buy", label: "Buy a kente strip", detail: "Handwoven. Red, gold, and a price you feel in the wallet.", minutes: 40, cost: 180, effects: { fun: 14, social: 8 }, emoji: "🟨" }),
      act({ id: "bonwire-watch", label: "Watch the weave", detail: "The loom clicks. You stop talking so you can hear it.", minutes: 25, effects: { fun: 12 }, emoji: "🧵" }),
    ],
  },
  {
    id: "tech-junction",
    name: "Tech Junction",
    emoji: "🍛",
    x: 1340,
    y: 300,
    group: "hang",
    town: "kumasi",
    blurb: "The gate of KNUST. Waakye, trotros, and everybody who is late for a lecture.",
    actions: [
      plate("tech-waakye", "Waakye in a leaf", "Egg, shito, and a curb to sit on.", 14, 38),
      act({ id: "tech-trotro", label: "Catch the campus trotro", detail: "You stand until somebody shifts a bag.", minutes: 25, cost: 5, effects: { social: 8, energy: -4 }, emoji: "🚐" }),
    ],
  },
  {
    id: "komfo-anokye",
    name: "Komfo Anokye",
    emoji: "🏥",
    x: 360,
    y: 520,
    group: "civic",
    town: "kumasi",
    blurb: "Bantama. Komfo Anokye Teaching Hospital. The big one. You come for a person, or before a small thing becomes a big thing.",
    actions: [
      act({ id: "kath-nurse", label: "See a nurse", detail: "Vitals, advice, and a receipt.", minutes: 50, cost: 30, effects: { energy: 18, hygiene: 6 }, emoji: "🏥" }),
      act({ id: "kath-visit", label: "Visit the ward", detail: "You brought malt. That is the love language.", minutes: 40, effects: { social: 18, fun: 4 }, social: true, emoji: "🥤" }),
    ],
  },
  {
    id: "ahodwo-gym",
    name: "Ahodwo Gym",
    emoji: "🏋️",
    x: 1280,
    y: 1000,
    group: "work",
    town: "kumasi",
    blurb: "Ahodwo. Mirrors, afrobeats, and a rack that does not care what you did yesterday.",
    actions: [
      act({ id: "ahodwo-train", label: "Train", detail: "Sweat honestly. The fan is trying.", minutes: 60, cost: 25, effects: { energy: -18, hygiene: -16, fun: 6 }, skill: "fitness", tag: "gym", emoji: "🏋️" }),
      act({ id: "ahodwo-class", label: "Join the evening class", detail: "Afrobeats, a mirror, and a set you feel tomorrow.", minutes: 50, cost: 30, effects: { energy: -16, hygiene: -14, fun: 10 }, skill: "fitness", tag: "gym", emoji: "💪" }),
    ],
  },
  {
    id: "kumasi-mall",
    name: "Kumasi City Mall",
    emoji: "🛍️",
    x: 860,
    y: 1000,
    group: "hang",
    town: "kumasi",
    blurb: "Lake Road. Cinema, cold air, and a food court that smells like every region at once.",
    actions: [
      act({ id: "kcm-film", label: "Catch a film", detail: "A ticket, a cold drink, and the lights going down.", minutes: 120, cost: 40, effects: { fun: 26, energy: -6 }, emoji: "🎬" }),
      plate("kcm-court", "Food court", "A tray number and something hot.", 32, 34),
      act({ id: "kcm-walk", label: "Walk the shops", detail: "Look at the price. Put it back. Repeat.", minutes: 35, effects: { fun: 10, social: 6 }, emoji: "🛍️" }),
    ],
  },
  {
    id: "cultural-centre",
    name: "Cultural Centre",
    emoji: "🥁",
    x: 300,
    y: 260,
    group: "hang",
    town: "kumasi",
    blurb: "Bantama. Drums, craft stalls, and a courtyard that fills when the city has something to say.",
    actions: [
      act({ id: "culture-drums", label: "Listen to the drums", detail: "You stay for one piece and then another.", minutes: 40, cost: 10, effects: { fun: 18, social: 10 }, skill: "music", emoji: "🥁" }),
      act({ id: "culture-craft", label: "Browse the craft stalls", detail: "Wood, beads, and a carver who lets you watch.", minutes: 30, cost: 20, effects: { fun: 12, social: 6 }, emoji: "🪵" }),
    ],
  },
  {
    id: "rattray",
    name: "Rattray Park",
    emoji: "🌳",
    x: 1600,
    y: 760,
    group: "sea",
    town: "kumasi",
    blurb: "Nhyiaeso. A paid park with a lake, a path, and families who came to sit down.",
    actions: [
      act({ id: "rattray-walk", label: "Walk the lake path", detail: "Ducks, a bridge, and shade that actually works.", minutes: 45, cost: 15, effects: { fun: 18, energy: 4, social: 6 }, emoji: "🌳" }),
      plate("rattray-snack", "Park snack", "Something fried and a cold sachet drink.", 12, 16),
    ],
  },
  {
    id: "suame",
    name: "Suame Magazine",
    emoji: "🔧",
    x: 960,
    y: 220,
    group: "work",
    town: "kumasi",
    blurb: "Suame. The spare-parts city. Engines, apprentices, and a lane that smells like oil and rain.",
    actions: [
      act({ id: "suame-walk", label: "Walk the magazine", detail: "Every shop can fix the thing the last shop could not.", minutes: 40, effects: { fun: 10, social: 8, hygiene: -6 }, emoji: "🔧" }),
      act({ id: "suame-part", label: "Ask for a part", detail: "They know the year of the car before you finish the sentence.", minutes: 25, cost: 40, effects: { social: 8 }, skill: "hustle", emoji: "⚙️" }),
    ],
  },
];
